const authBase=(import.meta.env.VITE_API_URL||'/api/auth').replace(/\/$/,'');
let authMode='login';
const authOverlay=document.querySelector('#auth-overlay'),authForm=document.querySelector('#auth-form');
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function paintUser(user){document.querySelector('#auth-open').hidden=Boolean(user);document.querySelector('#profile-button').hidden=!user;if(user){document.querySelector('#profile-name').textContent=user.name;document.querySelector('#profile-avatar').textContent=(user.name||'R').trim().charAt(0).toUpperCase();document.querySelector('#profile-points').textContent=typeof balance==='number'?new Intl.NumberFormat('en-US').format(balance):'1,500';document.querySelector('#account-note').innerHTML='เข้าสู่ระบบแล้ว: '+escapeHtml(user.name).toUpperCase()+'.<br />พร้อมติดตามคู่ชกที่คุณชื่นชอบ'}else document.querySelector('#account-note').innerHTML='เข้าสู่ระบบเพื่อบันทึกโปรไฟล์<br />ใช้แต้มจำลองในการทายผลเท่านั้น'}
function setAuthMode(mode,clearError=true){authMode=mode;document.querySelectorAll('.auth-tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));document.querySelector('.name-field').hidden=mode==='login';authForm.elements.name.required=mode==='register';authForm.elements.password.autocomplete=mode==='register'?'new-password':'current-password';document.querySelector('#auth-title').textContent=mode==='register'?'สมัครสมาชิก RING':'เข้าสู่ระบบ RING';document.querySelector('#auth-submit').innerHTML=mode==='register'?'สมัครสมาชิก <span>→</span>':'เข้าสู่ระบบ <span>→</span>';if(clearError)document.querySelector('#auth-error').textContent=''}
function openAuth(){authOverlay.classList.add('show');authOverlay.setAttribute('aria-hidden','false');setTimeout(()=>authForm.elements.email.focus(),30)}
function closeAuth(){authOverlay.classList.remove('show');authOverlay.setAttribute('aria-hidden','true')}
document.querySelector('#auth-open').onclick=openAuth;document.querySelector('#auth-close').onclick=closeAuth;authOverlay.onclick=e=>{if(e.target===authOverlay)closeAuth()};document.querySelectorAll('.auth-tab').forEach(t=>t.onclick=()=>setAuthMode(t.dataset.mode));
document.querySelector('#profile-button').onclick=e=>{if(e.target.closest('#signout'))return;document.querySelector('#profile-button').classList.toggle('menu-open')};document.querySelector('#profile-button').onkeydown=e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.currentTarget.classList.toggle('menu-open')}};
document.querySelector('#signout').onclick=e=>{e.stopPropagation();localStorage.removeItem('ring-auth-token');paintUser(null);document.querySelector('#profile-button').classList.remove('menu-open')};
authForm.onsubmit=async e=>{e.preventDefault();if(document.querySelector('#auth-submit').disabled)return;const submit=document.querySelector('#auth-submit'),data=Object.fromEntries(new FormData(authForm));document.querySelector('#auth-error').textContent='';submit.disabled=true;document.querySelectorAll('.auth-tab').forEach(t=>t.disabled=true);submit.textContent='กำลังเชื่อมต่อ…';try{const response=await fetch(`${authBase}/${authMode==='register'?'register':'login'}`,{method:'POST',signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error((response.status>=500?'ระบบเข้าสู่ระบบยังไม่พร้อมใช้งาน กรุณาลองใหม่ภายหลัง':result.message)||'เข้าสู่ระบบไม่สำเร็จ กรุณาตรวจสอบข้อมูลแล้วลองอีกครั้ง');if(!result.token||!result.user)throw new Error('ระบบตอบกลับไม่ครบถ้วน กรุณาลองอีกครั้ง');localStorage.setItem('ring-auth-token',result.token);paintUser(result.user);closeAuth();authForm.reset();toast(authMode==='register'?'สมัครสมาชิกสำเร็จ':'ยินดีต้อนรับกลับ คุณ'+result.user.name.toUpperCase())}catch(error){document.querySelector('#auth-error').textContent=error.name==='TimeoutError'?'การเชื่อมต่อใช้เวลานานเกินไป กรุณาลองอีกครั้ง':error.message==='Failed to fetch'?'เชื่อมต่อระบบไม่ได้ กรุณาตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง':error.message}finally{submit.disabled=false;setAuthMode(authMode,false);document.querySelectorAll('.auth-tab').forEach(t=>t.disabled=false)}};
async function restoreSession(){const token=localStorage.getItem('ring-auth-token');if(!token)return;try{const response=await fetch(`${authBase}/me`,{headers:{Authorization:`Bearer ${token}`}});if(response.status===401){localStorage.removeItem('ring-auth-token');return}if(!response.ok)return;paintUser((await response.json()).user)}catch{/* Keep the session when the server is temporarily unavailable. */}}
setAuthMode('login');restoreSession();
const eventAt=new Date('2026-09-26T19:30:00+07:00').getTime();function tickCountdown(){const left=Math.max(0,eventAt-Date.now()),day=Math.floor(left/86400000),hour=Math.floor(left%86400000/3600000),minute=Math.floor(left%3600000/60000),second=Math.floor(left%60000/1000);document.querySelector('#countdown').textContent=left?`${String(day).padStart(2,'0')}d ${String(hour).padStart(2,'0')}h ${String(minute).padStart(2,'0')}m ${String(second).padStart(2,'0')}s`:'FIGHT NIGHT'}tickCountdown();setInterval(tickCountdown,1000);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAuth();close();document.querySelector('#profile-button').classList.remove('menu-open')}});

const matches=[
{id:1,date:'26 SEP · 19:30',type:'MUAY THAI',title:'NIGHT SHIFT 08',division:'FLYWEIGHT · 135 LBS',a:{name:'ธันวา สายฟ้า',country:'THA',record:'18–3',win:78,ko:'9 KO',reach:'170 cm',style:'TECHNICIAN',form:['W · KO R2','W · DEC','W · TKO R3','L · DEC','W · KO R1']},b:{name:'มาร์โก เด ลา ครูซ',country:'ESP',record:'14–2',win:71,ko:'7 KO',reach:'173 cm',style:'PRESSURE',form:['W · DEC','W · KO R1','L · DEC','W · TKO R2','W · DEC']},image:'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1200&q=90'},
{id:2,date:'03 OCT · 20:00',type:'MMA',title:'CAGE THEORY 12',division:'LIGHTWEIGHT · 155 LBS',a:{name:'คิริน วงศ์วานิช',country:'THA',record:'11–1',win:84,ko:'5 KO',reach:'177 cm',style:'GRAPPLER',form:['W · SUB R2','W · DEC','W · TKO R1','W · SUB R3','L · DEC']},b:{name:'อาเดรียน โคล',country:'AUS',record:'16–5',win:64,ko:'8 KO',reach:'180 cm',style:'STRIKER',form:['L · DEC','W · KO R2','W · KO R1','W · DEC','L · SUB R2']},image:'https://images.unsplash.com/photo-1564419434663-c49967363849?auto=format&fit=crop&w=1200&q=90'},
{id:3,date:'10 OCT · 19:30',type:'MUAY THAI',title:'NIGHT SHIFT 09',division:'BANTAMWEIGHT · 145 LBS',a:{name:'ปกรณ์ นครสวรรค์',country:'THA',record:'22–6',win:66,ko:'12 KO',reach:'175 cm',style:'CLINCH',form:['W · TKO R3','L · DEC','W · KO R2','W · DEC','W · KO R1']},b:{name:'ลูคัส วอล์คเกอร์',country:'GBR',record:'19–4',win:73,ko:'10 KO',reach:'178 cm',style:'COUNTER',form:['W · DEC','W · KO R3','L · DEC','W · KO R2','W · DEC']},image:'https://images.unsplash.com/photo-1591117207239-788bf8de6c3b?auto=format&fit=crop&w=1200&q=90'}];
const $=s=>document.querySelector(s);let balance=Number(localStorage.getItem('strike-balance')||1500),picks=JSON.parse(localStorage.getItem('strike-picks')||'[]'),activeType='all',expandedMatch=null;const format=n=>new Intl.NumberFormat('th-TH').format(n);const save=()=>{localStorage.setItem('strike-balance',balance);localStorage.setItem('strike-picks',JSON.stringify(picks))};
function history(f){return `<div class="form-guide"><p>ผลงาน 5 นัดล่าสุด <span>${f.name}</span></p><div>${f.form.map(r=>`<span class="${r[0]==='W'?'win':'loss'}" title="${r}">${r[0]}</span>`).join('')}</div><small>${f.form.join(' · ')}</small></div>`}function stats(m){let rows=[['อัตราชนะ',`${m.a.win}%`,`${m.b.win}%`],['ชนะน็อก',m.a.ko,m.b.ko],['ช่วงชก',m.a.reach,m.b.reach],['สไตล์การชก',m.a.style,m.b.style]];return `<section class="stats-drawer"><div class="drawer-title"><span>ข้อมูลนักกีฬา</span><b>สถิติก่อนชก</b></div><div class="stat-compare">${rows.map(r=>`<div><strong>${r[1]}</strong><span>${r[0]}</span><strong>${r[2]}</strong></div>`).join('')}</div><div class="history-grid">${history(m.a)}${history(m.b)}</div></section>`}
function card(m){let p=picks.find(x=>x.matchId===m.id),open=expandedMatch===m.id;return `<article class="match-card"><div class="match-cover" style="background-image:linear-gradient(90deg,#08090dbf,#08090d24),url('${m.image}')"><span>${m.type}</span><p>${m.date}</p><h3>${m.title}</h3><i>RING//PULSE ORIGINAL</i></div><div class="match-body"><div class="match-label"><span>${m.division}</span><button class="stats-button ${open?'open':''}" data-stats="${m.id}">${open?'ซ่อนสถิติ −':'ดูสถิตินักกีฬา +'}</button></div><div class="fighters"><button class="fighter ${p?.fighter==='a'?'selected':''}" data-pick="a" data-match="${m.id}"><small>${m.a.country}</small><strong>${m.a.name}</strong><em>${m.a.record}</em><i>${m.a.win}% อัตราชนะ</i></button><b>VS</b><button class="fighter ${p?.fighter==='b'?'selected':''}" data-pick="b" data-match="${m.id}"><small>${m.b.country}</small><strong>${m.b.name}</strong><em>${m.b.record}</em><i>${m.b.win}% อัตราชนะ</i></button></div>${open?stats(m):''}<div class="pick-area"><label><span>แต้มที่ใช้</span><input type="number" min="10" step="10" value="${p?.stake||100}" data-stake="${m.id}" /></label><button class="add-pick ${p?'added':''}" data-add="${m.id}" ${p?'':'disabled'}>${p?'✓ เพิ่มในรายการแล้ว':'เลือกนักกีฬา'}</button></div></div></article>`}
function renderMatches(){let shown=matches.filter(m=>activeType==='all'||m.type===activeType);$('#event-list').innerHTML=shown.map(card).join('');bind()};function bind(){document.querySelectorAll('.fighter').forEach(b=>b.onclick=()=>{let id=+b.dataset.match,p=picks.find(x=>x.matchId===id);p?p.fighter=b.dataset.pick:picks.push({matchId:id,fighter:b.dataset.pick,stake:100});save();renderMatches();renderSlip()});document.querySelectorAll('[data-stake]').forEach(i=>i.oninput=()=>{let p=picks.find(x=>x.matchId===+i.dataset.stake);if(p){p.stake=Math.max(10,+i.value||10);save();renderSlip()}});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{$('#slip').classList.add('open');$('#scrim').classList.add('show')});document.querySelectorAll('[data-stats]').forEach(b=>b.onclick=()=>{expandedMatch=expandedMatch===+b.dataset.stats?null:+b.dataset.stats;renderMatches()})}
function renderSlip(){let total=picks.reduce((s,p)=>s+p.stake,0);$('#slip-count').textContent=picks.length;$('#chosen-count').textContent=picks.length;$('#stake-total').textContent=`${format(total)} แต้ม`;$('#confirm-picks').disabled=!picks.length;$('#slip-items').innerHTML=picks.length?picks.map(p=>{let m=matches.find(x=>x.id===p.matchId),f=m[p.fighter];return `<article class="slip-item"><button data-remove="${m.id}">×</button><small>${m.title} · ${m.date}</small><b>${f.name}</b><div><span>${format(p.stake)} แต้ม</span><em>นักกีฬาที่เลือก</em></div></article>`}).join(''):'<p class="empty">NO PICKS เพิ่มในรายการแล้ว<br /><small>เลือกนักกีฬาจากรายการแมตช์</small></p>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{picks=picks.filter(p=>p.matchId!==+b.dataset.remove);save();renderMatches();renderSlip()})}
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}function updateBalance(){$('#balance').textContent=format(balance);$('#balance-large').childNodes[0].nodeValue=`${format(balance)} `};$('.filter-row').onclick=e=>{if(!e.target.matches('.filter'))return;$('.filter.active').classList.remove('active');e.target.classList.add('active');activeType=e.target.dataset.type;expandedMatch=null;renderMatches()};$('#open-slip').onclick=()=>{$('#slip').classList.add('open');$('#scrim').classList.add('show')};let close=()=>{$('#slip').classList.remove('open');$('#scrim').classList.remove('show')};$('#close-slip').onclick=close;$('#scrim').onclick=close;$('#confirm-picks').onclick=()=>{let total=picks.reduce((s,p)=>s+p.stake,0);if(total>balance)return toast('แต้มคงเหลือไม่เพียงพอ');balance-=total;picks=[];save();updateBalance();renderMatches();renderSlip();close();toast(`ยืนยันแล้ว · ใช้ ${format(total)} แต้ม`)};$('#copy-contact').onclick=async()=>{try{await navigator.clipboard.writeText('hello@ringpulse.example');toast('คัดลอกอีเมลแล้ว')}catch{toast('EMAIL: hello@ringpulse.example')}};updateBalance();renderMatches();renderSlip();
