const matches = [
  { id: 1, date: '26 ก.ย. · 19:30', type: 'Muay Thai', title: 'NIGHT SHIFT 08', division: 'มวยไทย · ฟลายเวต', a: { name: 'ธันวา สายฟ้า', country: 'THA', record: '18–3', win: 78, ko: '9 KO', reach: '170 cm', style: 'มวยฝีมือ' }, b: { name: 'มาร์โก เด ลา ครูซ', country: 'ESP', record: '14–2', win: 71, ko: '7 KO', reach: '173 cm', style: 'มวยบู๊' }, image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1100&q=85' },
  { id: 2, date: '03 ต.ค. · 20:00', type: 'MMA', title: 'CAGE THEORY 12', division: 'MMA · ไลต์เวต', a: { name: 'คิริน วงศ์วานิช', country: 'THA', record: '11–1', win: 84, ko: '5 KO', reach: '177 cm', style: 'Grappler' }, b: { name: 'อาเดรียน โคล', country: 'AUS', record: '16–5', win: 64, ko: '8 KO', reach: '180 cm', style: 'Striker' }, image: 'https://images.unsplash.com/photo-1564419434663-c49967363849?auto=format&fit=crop&w=1100&q=85' },
  { id: 3, date: '10 ต.ค. · 19:30', type: 'Muay Thai', title: 'NIGHT SHIFT 09', division: 'มวยไทย · แบนตัมเวต', a: { name: 'ปกรณ์ นครสวรรค์', country: 'THA', record: '22–6', win: 66, ko: '12 KO', reach: '175 cm', style: 'เข่าใน' }, b: { name: 'ลูคัส วอล์คเกอร์', country: 'GBR', record: '19–4', win: 73, ko: '10 KO', reach: '178 cm', style: 'Counter' }, image: 'https://images.unsplash.com/photo-1517438322307-e67111335449?auto=format&fit=crop&w=1100&q=85' }
];
const $ = selector => document.querySelector(selector);
let balance = Number(localStorage.getItem('strike-balance') || 1500);
let picks = JSON.parse(localStorage.getItem('strike-picks') || '[]');
let activeType = 'all';
const format = number => new Intl.NumberFormat('th-TH').format(number);
function save() { localStorage.setItem('strike-balance', balance); localStorage.setItem('strike-picks', JSON.stringify(picks)); }
function card(match) { const picked = picks.find(p => p.matchId === match.id); return `<article class="match-card"><div class="match-cover" style="background-image:linear-gradient(90deg,#08090da8,#08090d36),url('${match.image}')"><span>${match.type}</span><p>${match.date}</p><h3>${match.title}</h3></div><div class="match-body"><div class="match-label"><span>${match.division}</span><button class="stats-button" data-stats="${match.id}">ดูสถิติก่อนชก ↗</button></div><div class="fighters"><button class="fighter ${picked?.fighter === 'a' ? 'selected' : ''}" data-pick="a" data-match="${match.id}"><small>${match.a.country}</small><strong>${match.a.name}</strong><em>${match.a.record}</em><i>${match.a.win}% WIN RATE</i></button><b>VS</b><button class="fighter ${picked?.fighter === 'b' ? 'selected' : ''}" data-pick="b" data-match="${match.id}"><small>${match.b.country}</small><strong>${match.b.name}</strong><em>${match.b.record}</em><i>${match.b.win}% WIN RATE</i></button></div><div class="pick-area"><label>ใช้แต้ม <input type="number" min="10" step="10" value="${picked?.stake || 100}" data-stake="${match.id}" /></label><button class="add-pick ${picked ? 'added' : ''}" data-add="${match.id}" ${picked ? '' : 'disabled'}>${picked ? 'เลือกแล้ว ✓' : 'เลือกนักกีฬาก่อน'}</button></div></div></article>`; }
function renderMatches() { const shown = matches.filter(m => activeType === 'all' || m.type === activeType); $('#event-list').innerHTML = shown.map(card).join(''); bindMatchActions(); }
function bindMatchActions() { document.querySelectorAll('.fighter').forEach(btn => btn.onclick = () => { const matchId = Number(btn.dataset.match), chosen = btn.dataset.pick, old = picks.find(p => p.matchId === matchId); if (old) old.fighter = chosen; else picks.push({ matchId, fighter: chosen, stake: 100 }); save(); renderMatches(); renderSlip(); }); document.querySelectorAll('[data-stake]').forEach(input => input.oninput = () => { const pick = picks.find(p => p.matchId === Number(input.dataset.stake)); if (pick) { pick.stake = Math.max(10, Number(input.value) || 10); save(); renderSlip(); } }); document.querySelectorAll('[data-add]').forEach(btn => btn.onclick = () => showToast('เพิ่มตัวเลือกลงในบัตรแล้ว')); document.querySelectorAll('[data-stats]').forEach(btn => btn.onclick = () => openStats(Number(btn.dataset.stats))); }
function renderSlip() { const total = picks.reduce((sum, pick) => sum + pick.stake, 0); $('#slip-count').textContent = picks.length; $('#chosen-count').textContent = picks.length; $('#stake-total').textContent = `${format(total)} PTS`; $('#confirm-picks').disabled = !picks.length; $('#slip-items').innerHTML = picks.length ? picks.map(pick => { const match = matches.find(m => m.id === pick.matchId), fighter = match[pick.fighter]; return `<article class="slip-item"><button data-remove="${match.id}" aria-label="ลบ">×</button><small>${match.title}</small><b>${fighter.name}</b><div><span>${format(pick.stake)} PTS</span><em>เลือกผู้ชนะ</em></div></article>`; }).join('') : '<p class="empty">ยังไม่ได้เลือกนักกีฬา<br /><small>เลือกจากรายการแมตช์ด้านซ้าย</small></p>'; document.querySelectorAll('[data-remove]').forEach(btn => btn.onclick = () => { picks = picks.filter(p => p.matchId !== Number(btn.dataset.remove)); save(); renderMatches(); renderSlip(); }); }
function updateBalance() { $('#balance').textContent = format(balance); $('#balance-large').childNodes[0].nodeValue = `${format(balance)} `; }
function openStats(id) { const match = matches.find(m => m.id === id), rows = [['สถิติชนะ', `${match.a.win}%`, `${match.b.win}%`], ['ชนะน็อก', match.a.ko, match.b.ko], ['ช่วงชก', match.a.reach, match.b.reach], ['สไตล์', match.a.style, match.b.style]]; $('#stats-content').innerHTML = `<p class="eyebrow red">HEAD TO HEAD · ${match.division}</p><h2>${match.a.name}<i> VS </i>${match.b.name}</h2><div class="stat-names"><b>${match.a.country} · ${match.a.record}</b><b>${match.b.country} · ${match.b.record}</b></div><div class="stat-table">${rows.map(row => `<div><strong>${row[1]}</strong><span>${row[0]}</span><strong>${row[2]}</strong></div>`).join('')}</div><p class="disclaimer">ข้อมูลใช้สำหรับการวิเคราะห์และความบันเทิงเท่านั้น</p>`; $('#stats-modal').showModal(); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
$('.filter-row').onclick = event => { if (!event.target.matches('.filter')) return; $('.filter.active').classList.remove('active'); event.target.classList.add('active'); activeType = event.target.dataset.type; renderMatches(); };
$('#open-slip').onclick = () => { $('#slip').classList.add('open'); $('#scrim').classList.add('show'); }; const closeSlip = () => { $('#slip').classList.remove('open'); $('#scrim').classList.remove('show'); }; $('#close-slip').onclick = closeSlip; $('#scrim').onclick = closeSlip; $('#close-modal').onclick = () => $('#stats-modal').close();
$('#confirm-picks').onclick = () => { const total = picks.reduce((sum, pick) => sum + pick.stake, 0); if (total > balance) return showToast('แต้มคงเหลือไม่เพียงพอ'); balance -= total; picks = []; save(); updateBalance(); renderMatches(); renderSlip(); closeSlip(); showToast(`บันทึกการเลือกแล้ว ใช้ ${format(total)} แต้ม`); };
$('#copy-contact').onclick = async () => { try { await navigator.clipboard.writeText('hello@strikegrid.example'); showToast('คัดลอกอีเมลแล้ว'); } catch { showToast('อีเมล: hello@strikegrid.example'); } };
updateBalance(); renderMatches(); renderSlip();
