// Run with Node.js 22+ while Vite and a headless Chrome with --remote-debugging-port=9333 are running.
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const tabs = await (await fetch('http://127.0.0.1:9333/json/list')).json();
const tab = tabs.find(t => t.type === 'page');
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise(resolve => ws.addEventListener('open', resolve, {once:true}));
let sequence = 0; const pending = new Map(), errors = [];
ws.addEventListener('message', event => { const message = JSON.parse(event.data); if(message.id) { const task=pending.get(message.id); pending.delete(message.id); if(message.error) task.reject(new Error(JSON.stringify(message.error))); else task.resolve(message.result); } if(message.method==='Runtime.exceptionThrown') errors.push(message.params.exceptionDetails.text); });
const send = (method,params={}) => new Promise((resolve,reject) => { const id=++sequence; pending.set(id,{resolve,reject}); ws.send(JSON.stringify({id,method,params})); });
const evaluate = async expression => { const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true}); if(result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails)); return result.result.value; };
const navigate = async (method,params={}) => { const loaded=new Promise(resolve => { const handler=event => { if(JSON.parse(event.data).method==='Page.loadEventFired'){ws.removeEventListener('message',handler);resolve();} };ws.addEventListener('message',handler); }); await send(method,params); await loaded; };
const waitFor = async expression => { for(let i=0;i<100;i++){ if(await evaluate(expression)) return; await new Promise(r=>setTimeout(r,100)); } throw new Error('Timed out: '+expression); };
try {
  await send('Runtime.enable'); await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await navigate('Page.navigate',{url:'http://127.0.0.1:5174'});
  await waitFor('document.querySelectorAll(".match-card").length===3');
  await evaluate('localStorage.clear()'); await navigate('Page.reload');
  await waitFor('document.querySelectorAll(".match-card").length===3');
  assert.equal(await evaluate('document.querySelectorAll(".athlete-card").length'),6);
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'desktop overflow');
  await evaluate('document.querySelector("#book-ticket").click()');
  assert.equal(await evaluate('document.querySelector("#ticket-dialog").open'),true);
  assert.equal(await evaluate('document.querySelector("#ticket-total").textContent'),'฿800');
  await evaluate('document.querySelector("[value=ringside]").click(); var q=document.querySelector("[name=quantity]");q.value="3";q.dispatchEvent(new Event("change",{bubbles:true}))');
  assert.equal(await evaluate('document.querySelector("#ticket-total").textContent'),'฿7,500');
  assert.equal(await evaluate('document.querySelector("#ticket-form").checkValidity()'),false,'empty form must be invalid');
  await evaluate('document.querySelector("[name=holder]").value="ผู้ชม <img src=x onerror=alert(1)>"; document.querySelector("#ticket-form input[type=checkbox]").checked=true;document.querySelector("#ticket-form").requestSubmit()');
  assert.equal(await evaluate('document.querySelector("#content-dialog").open'),true);
  assert.equal(await evaluate('document.querySelectorAll(".ticket-receipt img").length'),0,'holder must be escaped');
  assert.equal(await evaluate('JSON.parse(localStorage.getItem("ring-tickets-v1"))[0].quantity'),3);
  await evaluate('document.querySelector("#content-dialog").close()');
  await navigate('Page.reload'); await waitFor('document.querySelectorAll(".match-card").length===3');
  await evaluate('document.querySelector("#my-tickets").click()');
  assert.equal(await evaluate('document.querySelectorAll(".ticket-receipt").length'),1,'ticket survives reload');
  await evaluate('document.querySelector("#content-dialog").close(); document.querySelector(".filter[data-type=kickboxing]").click()');
  assert.equal(await evaluate('document.querySelectorAll(".match-card").length'),1);
  await evaluate('document.querySelector(".filter[data-type=all]").click();var s=document.querySelector("#match-search");s.value="รถถัง";s.dispatchEvent(new Event("input"))');
  assert.equal(await evaluate('document.querySelectorAll(".match-card").length'),1);
  await evaluate('document.querySelector("[data-pick=a]").click();var i=document.querySelector("[data-stake]");i.value="15";i.dispatchEvent(new Event("input",{bubbles:true}))');
  assert.equal(await evaluate('document.querySelector("#confirm-picks").disabled'),true,'invalid stake blocked');
  await evaluate('var i=document.querySelector("[data-stake]");i.value="100";i.dispatchEvent(new Event("input",{bubbles:true}));document.querySelector("#confirm-picks").click()');
  assert.equal(await evaluate('document.querySelector("#balance").textContent'),'1,400');
  await evaluate('document.querySelector("#open-history").click()');
  assert.equal(await evaluate('document.querySelectorAll("#content-body .slip-item").length'),1);
  await evaluate('document.querySelector("#content-dialog").close();document.querySelector("#auth-open").click();document.querySelector("[data-mode=register]").click()');
  assert.equal(await evaluate('document.querySelector("#auth-form").elements.name.required'),true);
  await evaluate('document.querySelector("#auth-dialog").close();document.querySelector("[data-article]").click()');
  assert.equal(await evaluate('document.querySelector("#content-dialog").open'),true);
  await evaluate('document.querySelector("#content-dialog").close();var s=document.querySelector("#match-search");s.value="";s.dispatchEvent(new Event("input"));scrollTo(0,0)');
  const desktop=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(join(tmpdir(),'ring-desktop.png'),Buffer.from(desktop.data,'base64'));
  for(const width of [390,320,768]) {
    await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
    assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,`overflow at ${width}`);
  }
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await evaluate('document.querySelector("#menu-toggle").click()');
  assert.equal(await evaluate('document.querySelector("#menu-toggle").getAttribute("aria-expanded")'),'true');
  await evaluate('document.querySelector("#main-nav a").click();document.querySelector("#book-ticket").click()');
  assert.equal(await evaluate('document.querySelector("#ticket-dialog").scrollWidth<=document.querySelector("#ticket-dialog").clientWidth'),true,'mobile dialog overflow');
  const mobile=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(join(tmpdir(),'ring-mobile-booking.png'),Buffer.from(mobile.data,'base64'));
  await evaluate('document.querySelector("#ticket-dialog").close();localStorage.setItem("ring-tickets-v1","broken json");localStorage.setItem("ring-game-v1","broken json")');
  await navigate('Page.reload'); await waitFor('document.querySelectorAll(".match-card").length===3');
  assert.equal(await evaluate('document.querySelector("#balance").textContent'),'1,500','corrupt storage fallback');
  assert.deepEqual(errors,[],'browser JavaScript errors');
  console.log('PASS: desktop/mobile layout, 6 athlete links, booking prices, validation, escaping, persistence, filtering, picks, history, auth tabs, articles, corrupt storage recovery; no JS errors.');
  console.log('Screenshots: '+join(tmpdir(),'ring-desktop.png')+'; '+join(tmpdir(),'ring-mobile-booking.png'));
} finally { ws.close(); }
